### ISSUE TITLE
Trying to build this-Questions.

### ISSUE THREAD

**Issue by t33xdr** [jerinpeter/4wdNavbot#1]
Great work. Could you add the wiring diagram? Curious on how to implement the skid steer(from navbot_description) . How to combine left [( front ,back) motors as one topic] & [right] as another while using individual controllers for four motors as you did. Noted that rmcs gets data from 2 slave ids -#2 & #4.Thanks.

**Comment by jerinpeter** [comment]
**Wiring**
Wiring is pretty straight forward
-  Assign unique Slave ID's to all 4 motors, you can do so by referring to the rmcs manual.
- Connect the TX, RX, GND of all the motors in parallel.
- From this connect to the TX, RX, and GND of the Arduino Mega.
- Upload the code, Specify the code in the code and you are good to GO!

**Skid Steer Implementation**
For the simulation, I have used the skid steer gazebo plugin. which takes care of everything and can accept cmd_vel and drive the Robot.

I have also implemented **diff_drive_controller**  from `ros_control` in the simulation but as it needs an hardware interface code, I haven't implemented that in the real robot.

You can refer to the code for the same [here](https://github.com/jerinpeter/navbot_diff_drive_control)

Currently,I haven't implemented a controller for the real robot. The RMCS 2303 motor drivers do have an inbuilt PID controller running in them which will do the RPM correction.

In the Arduino Code I have written, I have treated the **left** [front, back] and **right**[ front, back] as one and wrote code in such a way that left wheel and right velocity calculated goes to both the front and back wheels respectively.

**Comment by t33xdr** [comment]
Thanks for the prompt reply,Jerin. I'll supplement this info. by going through the RMCS docs.Cheers!
